mkdir -p 'Section 1- Course Introduction';
touch 'Section 1- Course Introduction/1. Course Introduction - Please Watch.md';
touch 'Section 1- Course Introduction/Quiz 1- Course Expectations Quiz.md';
touch 'Section 1- Course Introduction/2. About your instructor.md';
mkdir -p 'Section 2- Slides Download';
touch 'Section 2- Slides Download/3. Slides Download.md';
touch 'Section 2- Slides Download/Resources.md';
touch 'Section 2- Slides Download/Course Material Download.md';
mkdir -p 'Section 3- Identity & Federation';
touch 'Section 3- Identity & Federation/4. IAM.md';
touch 'Section 3- Identity & Federation/5. IAM Access Analyzer.md';
touch 'Section 3- Identity & Federation/6. STS.md';
touch 'Section 3- Identity & Federation/7. Identity Federation & Cognito.md';
touch 'Section 3- Identity & Federation/8. AWS Directory Services.md';
touch 'Section 3- Identity & Federation/9. AWS Organizations.md';
touch 'Section 3- Identity & Federation/10. AWS Organizations Policies.md';
touch 'Section 3- Identity & Federation/11. AWS IAM Identity Center.md';
touch 'Section 3- Identity & Federation/12. AWS Control Tower.md';
touch 'Section 3- Identity & Federation/13. AWS Resource Access Manager - RAM.md';
touch 'Section 3- Identity & Federation/14. Summary of Identity & Federation.md';
touch 'Section 3- Identity & Federation/Quiz 2- Identity & Federation Quiz.md';
mkdir -p 'Section 4- Security';
touch 'Section 4- Security/15. CloudTrail.md';
touch 'Section 4- Security/16. CloudTrail - EventBridge Integration.md';
touch 'Section 4- Security/17. CloudTrail - SA Pro.md';
touch 'Section 4- Security/18. KMS.md';
touch 'Section 4- Security/19. Parameter Store.md';
touch 'Section 4- Security/20. Secrets Manager.md';
touch 'Section 4- Security/21. RDS Security.md';
touch 'Section 4- Security/22. SSL Encryption, SNI & MITM.md';
touch 'Section 4- Security/23. AWS Certificate Manager - ACM.md';
touch 'Section 4- Security/24. CloudHSM.md';
touch 'Section 4- Security/25. Solution Architecture - SSL on ELB.md';
touch 'Section 4- Security/26. S3 Security.md';
touch 'Section 4- Security/27. S3 Access Points.md';
touch 'Section 4- Security/28. S3 Multi-Region Access Points.md';
touch 'Section 4- Security/29. S3 Multi-Region Access Points - Hands On.md';
touch 'Section 4- Security/30. S3 Object Lambda.md';
touch 'Section 4- Security/31. DDoS and AWS Shield.md';
touch 'Section 4- Security/32. AWS WAF - Web Application Firewall.md';
touch 'Section 4- Security/33. AWS Firewall Manager.md';
touch 'Section 4- Security/34. Blocking an IP Address.md';
touch 'Section 4- Security/35. Amazon Inspector.md';
touch 'Section 4- Security/36. AWS Config.md';
touch 'Section 4- Security/37. AWS Managed Logs.md';
touch 'Section 4- Security/38. Amazon GuardDuty.md';
touch 'Section 4- Security/39. IAM Advanced Policies.md';
touch 'Section 4- Security/40. EC2 Instance Connect.md';
touch 'Section 4- Security/41. AWS Security Hub.md';
touch 'Section 4- Security/42. Amazon Detective.md';
touch 'Section 4- Security/Quiz 3- Security Quiz.md';
mkdir -p 'Section 5- Compute & Load Balancing';
touch 'Section 5- Compute & Load Balancing/43. Solution Architecture on AWS.md';
touch 'Section 5- Compute & Load Balancing/44. EC2.md';
touch 'Section 5- Compute & Load Balancing/45. High Performance Computing (HPC).md';
touch 'Section 5- Compute & Load Balancing/46. Auto Scaling.md';
touch 'Section 5- Compute & Load Balancing/47. Auto Scaling Update Strategies.md';
touch 'Section 5- Compute & Load Balancing/48. Spot Instances & Spot Fleet.md';
touch 'Section 5- Compute & Load Balancing/49. Amazon ECS - Elastic Container Service.md';
touch 'Section 5- Compute & Load Balancing/50. Amazon ECR - Elastic Container Registry.md';
touch 'Section 5- Compute & Load Balancing/51. Amazon EKS - Elastic Kubernetes Service.md';
touch 'Section 5- Compute & Load Balancing/52. ECS Anywhere & EKS Anywhere.md';
touch 'Section 5- Compute & Load Balancing/53. AWS Lambda - Part 1.md';
touch 'Section 5- Compute & Load Balancing/54. AWS Lambda - Part 2.md';
touch 'Section 5- Compute & Load Balancing/55. Elastic Load Balancers - Part 1.md';
touch 'Section 5- Compute & Load Balancing/56. Elastic Load Balancers - Part 2.md';
touch 'Section 5- Compute & Load Balancing/57. API Gateway.md';
touch 'Section 5- Compute & Load Balancing/58. API Gateway - Part 2.md';
touch 'Section 5- Compute & Load Balancing/59. AWS AppSync.md';
touch 'Section 5- Compute & Load Balancing/60. Route 53 - Part 1.md';
touch 'Section 5- Compute & Load Balancing/61. Route 53 - Part 2.md';
touch 'Section 5- Compute & Load Balancing/62. Route 53 - Resolvers & Hybrid DNS.md';
touch 'Section 5- Compute & Load Balancing/63. AWS Global Accelerator.md';
touch 'Section 5- Compute & Load Balancing/64. Comparison of Solutions Architecture.md';
touch 'Section 5- Compute & Load Balancing/65. AWS Outposts.md';
touch 'Section 5- Compute & Load Balancing/66. AWS WaveLength.md';
touch 'Section 5- Compute & Load Balancing/67. AWS Local Zones.md';
touch 'Section 5- Compute & Load Balancing/Quiz 4- Compute & Load Balancing Quiz.md';
mkdir -p 'Section 6- Storage';
touch 'Section 6- Storage/68. EBS & Local Instance Store.md';
touch 'Section 6- Storage/69. Amazon EFS.md';
touch 'Section 6- Storage/70. Amazon S3.md';
touch 'Section 6- Storage/71. Amazon S3 - Storage Class Analysis.md';
touch 'Section 6- Storage/72. Amazon S3 - Storage Lens.md';
touch 'Section 6- Storage/73. S3 Solution Architecture.md';
touch 'Section 6- Storage/74. Amazon FSx.md';
touch 'Section 6- Storage/75. Amazon FSx - Solution Architectures.md';
touch 'Section 6- Storage/76. AWS DataSync.md';
touch 'Section 6- Storage/77. AWS DataSync - Solution Architecture.md';
touch 'Section 6- Storage/78. AWS Data Exchange.md';
touch 'Section 6- Storage/79. AWS Transfer Family.md';
touch 'Section 6- Storage/80. AWS Storage Services Price Comparison.md';
touch 'Section 6- Storage/Quiz 5- Storage Quiz.md';
mkdir -p 'Section 7- Caching';
touch 'Section 7- Caching/81. CloudFront - Part 1.md';
touch 'Section 7- Caching/82. CloudFront - Part 2.md';
touch 'Section 7- Caching/83. Lambda@Edge and CloudFront Functions.md';
touch 'Section 7- Caching/84. Lambda@Edge Reduce Latency.md';
touch 'Section 7- Caching/85. Amazon ElastiCache.md';
touch 'Section 7- Caching/86. Handling Extreme Rates.md';
touch 'Section 7- Caching/Quiz 6- Caching Quiz.md';
mkdir -p 'Section 8- Databases';
touch 'Section 8- Databases/87. DynamoDB.md';
touch 'Section 8- Databases/88. Amazon OpenSearch.md';
touch 'Section 8- Databases/89. RDS.md';
touch 'Section 8- Databases/90. Aurora - Part 1.md';
touch 'Section 8- Databases/91. Aurora - Part 2.md';
touch 'Section 8- Databases/Quiz 7- Databases Quiz.md';
mkdir -p 'Section 9- Service Communication';
touch 'Section 9- Service Communication/92. Step Functions.md';
touch 'Section 9- Service Communication/93. SQS.md';
touch 'Section 9- Service Communication/94. Amazon MQ.md';
touch 'Section 9- Service Communication/95. Amazon SNS.md';
touch 'Section 9- Service Communication/96. Amazon SNS - SQS Fan Out Pattern.md';
touch 'Section 9- Service Communication/97. Amazon SNS - Message Delivery Retries.md';
touch 'Section 9- Service Communication/Quiz 8- Service Communication Quiz.md';
mkdir -p 'Section 10- Data Engineering';
touch 'Section 10- Data Engineering/98. Amazon Kinesis Data Streams.md';
touch 'Section 10- Data Engineering/99. Amazon Data Firehose.md';
touch 'Section 10- Data Engineering/100. Amazon Managed Service for Apache Flink.md';
touch 'Section 10- Data Engineering/101. Streaming Architectures.md';
touch 'Section 10- Data Engineering/102. Amazon MSK.md';
touch 'Section 10- Data Engineering/103. AWS Batch.md';
touch 'Section 10- Data Engineering/104. Amazon EMR.md';
touch 'Section 10- Data Engineering/105. Running Jobs on AWS.md';
touch 'Section 10- Data Engineering/106. AWS Glue.md';
touch 'Section 10- Data Engineering/107. Redshift.md';
touch 'Section 10- Data Engineering/108. Amazon DocumentDB.md';
touch 'Section 10- Data Engineering/109. Amazon Timestream.md';
touch 'Section 10- Data Engineering/110. Amazon Athena.md';
touch 'Section 10- Data Engineering/111. Amazon QuickSight.md';
touch 'Section 10- Data Engineering/112. Big Data Architecture.md';
touch 'Section 10- Data Engineering/Quiz 9- Data Engineering Quiz.md';
mkdir -p 'Section 11- Monitoring';
touch 'Section 11- Monitoring/113. CloudWatch.md';
touch 'Section 11- Monitoring/114. CloudWatch Logs.md';
touch 'Section 11- Monitoring/115. Amazon EventBridge.md';
touch 'Section 11- Monitoring/116. X-Ray.md';
touch 'Section 11- Monitoring/117. AWS Personal Health Dashboard.md';
touch 'Section 11- Monitoring/Quiz 10- Monitoring Quiz.md';
mkdir -p 'Section 12- Deployment and Instance Management';
touch 'Section 12- Deployment and Instance Management/118. Elastic Beanstalk.md';
touch 'Section 12- Deployment and Instance Management/119. CodeDeploy.md';
touch 'Section 12- Deployment and Instance Management/120. CloudFormation.md';
touch 'Section 12- Deployment and Instance Management/121. Service Catalog.md';
touch 'Section 12- Deployment and Instance Management/122. SAM - Serverless Application Model.md';
touch 'Section 12- Deployment and Instance Management/123. AWS CDK - Cloud Development Kit.md';
touch 'Section 12- Deployment and Instance Management/124. AWS Systems Manager - SSM.md';
touch 'Section 12- Deployment and Instance Management/125. AWS Cloud Map.md';
touch 'Section 12- Deployment and Instance Management/Quiz 11- Deployment and Instance Management Quiz.md';
mkdir -p 'Section 13- Cost Control';
touch 'Section 13- Cost Control/126. Cost Allocation Tags.md';
touch 'Section 13- Cost Control/127. AWS Tag Editor.md';
touch 'Section 13- Cost Control/128. Trusted Advisor.md';
touch 'Section 13- Cost Control/129. AWS Service Quotas.md';
touch 'Section 13- Cost Control/130. EC2 Launch Types & Savings Plan.md';
touch 'Section 13- Cost Control/131. S3 Cost Savings.md';
touch 'Section 13- Cost Control/132. S3 Storage Classes - Reminder.md';
touch 'Section 13- Cost Control/133. AWS Budgets & Cost Explorer.md';
touch 'Section 13- Cost Control/134. AWS Compute Optimizer.md';
touch 'Section 13- Cost Control/135. EC2 Reserved Instance.md';
touch 'Section 13- Cost Control/Quiz 12- Cost Control Quiz.md';
mkdir -p 'Section 14- Migration';
touch 'Section 14- Migration/136. Cloud Migration Strategies - The 7Rs.md';
touch 'Section 14- Migration/137. Storage Gateway.md';
touch 'Section 14- Migration/138. Storage Gateway - Advanced Concepts.md';
touch 'Section 14- Migration/139. Snow Family.md';
touch 'Section 14- Migration/140. Snow Family - Improving Performance.md';
touch 'Section 14- Migration/141. AWS DMS - Database Migration Services.md';
touch 'Section 14- Migration/142. AWS CART - Cloud Adoption Readiness Tool.md';
touch 'Section 14- Migration/143. Disaster Recovery.md';
touch 'Section 14- Migration/144. AWS FIS - Fault Injection Simulator.md';
touch 'Section 14- Migration/145. VM Migrations Services.md';
touch 'Section 14- Migration/146. AWS Migration Evaluator.md';
touch 'Section 14- Migration/147. AWS Backup.md';
touch 'Section 14- Migration/Quiz 13- Migration Quiz.md';
mkdir -p 'Section 15- VPC';
touch 'Section 15- VPC/148. VPC - Basics.md';
touch 'Section 15- VPC/149. VPC Peering.md';
touch 'Section 15- VPC/150. Transit Gateway.md';
touch 'Section 15- VPC/151. VPC Endpoints.md';
touch 'Section 15- VPC/152. VPC Endpoint Policies.md';
touch 'Section 15- VPC/153. PrivateLink.md';
touch 'Section 15- VPC/154. AWS S2S VPN.md';
touch 'Section 15- VPC/155. AWS Client VPN.md';
touch 'Section 15- VPC/156. Direct Connect.md';
touch 'Section 15- VPC/157. On-Premise Redundant Connections.md';
touch 'Section 15- VPC/158. VPC Flow Logs.md';
touch 'Section 15- VPC/159. AWS Network Firewall.md';
touch 'Section 15- VPC/Quiz 14- VPC Quiz.md';
mkdir -p 'Section 16- Machine Learning';
touch 'Section 16- Machine Learning/160. Amazon Bedrock.md';
touch 'Section 16- Machine Learning/161. Rekognition Overview.md';
touch 'Section 16- Machine Learning/162. Transcribe Overview.md';
touch 'Section 16- Machine Learning/163. Polly Overview.md';
touch 'Section 16- Machine Learning/164. Translate Overview.md';
touch 'Section 16- Machine Learning/165. Lex + Connect Overview.md';
touch 'Section 16- Machine Learning/166. Comprehend Overview.md';
touch 'Section 16- Machine Learning/167. Comprehend Medical Overview.md';
touch 'Section 16- Machine Learning/168. SageMaker AI Overview.md';
touch 'Section 16- Machine Learning/169. Kendra Overview.md';
touch 'Section 16- Machine Learning/170. Personalize Overview.md';
touch 'Section 16- Machine Learning/171. Textract Overview.md';
touch 'Section 16- Machine Learning/172. Machine Learning Summary.md';
touch 'Section 16- Machine Learning/Quiz 15- Machine Learning Quiz.md';
mkdir -p 'Section 17- Other Services';
touch 'Section 17- Other Services/173. Other Services.md';
touch 'Section 17- Other Services/174. CICD.md';
touch 'Section 17- Other Services/175. Alexa for Business, Lex & Connect.md';
touch 'Section 17- Other Services/176. Kinesis Video Streams.md';
touch 'Section 17- Other Services/177. AWS WorkSpaces.md';
touch 'Section 17- Other Services/178. Amazon AppStream 2.0.md';
touch 'Section 17- Other Services/179. AWS Device Farm.md';
touch 'Section 17- Other Services/180. Amazon Macie.md';
touch 'Section 17- Other Services/181. Amazon SES.md';
touch 'Section 17- Other Services/182. Amazon Pinpoint.md';
touch 'Section 17- Other Services/183. EC2 Image Builder.md';
touch 'Section 17- Other Services/184. AWS IoT Core.md';
touch 'Section 17- Other Services/185. Other Services Summary.md';
touch 'Section 17- Other Services/Quiz 16- Other Services Quiz.md';
mkdir -p 'Section 18- Exam Preparation';
touch 'Section 18- Exam Preparation/186. Exam Walkthrough and Signup.md';
touch 'Section 18- Exam Preparation/187. Save 50% on your AWS Exam Cost!.md';
touch 'Section 18- Exam Preparation/188. Get an Extra 30 Minutes on your AWS Exam - Non Native English Speakers only.md';
touch 'Section 18- Exam Preparation/189. Exam Guide & Sample Questions.md';
touch 'Section 18- Exam Preparation/190. Note- Sample Questions here are for SAP-C02.md';
touch 'Section 18- Exam Preparation/191. Note about Sample Question 1.md';
touch 'Section 18- Exam Preparation/192. Sample Question 1.md';
touch 'Section 18- Exam Preparation/193. Sample Question 2.md';
touch 'Section 18- Exam Preparation/194. Sample Question 3.md';
touch 'Section 18- Exam Preparation/195. Sample Question 4.md';
touch 'Section 18- Exam Preparation/196. Sample Question 5.md';
touch 'Section 18- Exam Preparation/197. Sample Question 6.md';
touch 'Section 18- Exam Preparation/198. Sample Question 7.md';
touch 'Section 18- Exam Preparation/199. Sample Question 8.md';
touch 'Section 18- Exam Preparation/200. Sample Question 9.md';
mkdir -p 'Section 19- Congratulations';
touch 'Section 19- Congratulations/201. AWS Certification Paths.md';
touch 'Section 19- Congratulations/202. Congratulations.md';
touch 'Section 19- Congratulations/203. Bonus Lecture.md';
