mkdir -p 'Section 1- Course Introduction - AWS Certified Developer Associate';
touch 'Section 1- Course Introduction - AWS Certified Developer Associate/1. Course Introduction - AWS Certified Developer Associate.md';
touch 'Section 1- Course Introduction - AWS Certified Developer Associate/2. PLEASE READ- Lectures you can skip if you took a course from me before.md';
touch 'Section 1- Course Introduction - AWS Certified Developer Associate/3. Creating an AWS Account.md';
touch 'Section 1- Course Introduction - AWS Certified Developer Associate/4. AWS Account Activation Troubleshooting.md';
touch 'Section 1- Course Introduction - AWS Certified Developer Associate/5. Important Message.md';
touch 'Section 1- Course Introduction - AWS Certified Developer Associate/6. About your instructor.md';
mkdir -p 'Section 2- Code & Slides Download';
touch 'Section 2- Code & Slides Download/7. Code & Slides Download.md';
mkdir -p 'Section 3- Getting started with AWS';
touch 'Section 3- Getting started with AWS/8. AWS Cloud Overview - Regions & AZ.md';
touch 'Section 3- Getting started with AWS/9. [Important] AWS Console UI Update.md';
touch 'Section 3- Getting started with AWS/10. Tour of the AWS Console & Services in AWS.md';
mkdir -p 'Section 4- IAM & AWS CLI';
touch 'Section 4- IAM & AWS CLI/11. IAM Introduction- Users, Groups, Policies.md';
touch 'Section 4- IAM & AWS CLI/12. IAM Users & Groups Hands On.md';
touch 'Section 4- IAM & AWS CLI/13. AWS Console Simultaneous Sign-in.md';
touch 'Section 4- IAM & AWS CLI/14. IAM Policies.md';
touch 'Section 4- IAM & AWS CLI/15. IAM Policies Hands On.md';
touch 'Section 4- IAM & AWS CLI/16. IAM MFA Overview.md';
touch 'Section 4- IAM & AWS CLI/17. IAM MFA Hands On.md';
touch 'Section 4- IAM & AWS CLI/18. AWS Access Keys, CLI and SDK.md';
touch 'Section 4- IAM & AWS CLI/19. AWS CLI Setup on Windows.md';
touch 'Section 4- IAM & AWS CLI/20. AWS CLI Setup on Mac OS X.md';
touch 'Section 4- IAM & AWS CLI/21. AWS CLI Setup on Linux.md';
touch 'Section 4- IAM & AWS CLI/22. AWS CLI Hands On.md';
touch 'Section 4- IAM & AWS CLI/23. AWS CloudShell.md';
touch 'Section 4- IAM & AWS CLI/24. IAM Roles for AWS Services.md';
touch 'Section 4- IAM & AWS CLI/25. IAM Roles Hands On.md';
touch 'Section 4- IAM & AWS CLI/26. IAM Security Tools.md';
touch 'Section 4- IAM & AWS CLI/27. IAM Security Tools Hands On.md';
touch 'Section 4- IAM & AWS CLI/28. IAM Best Practices.md';
touch 'Section 4- IAM & AWS CLI/29. Shared Responsibility Model for IAM.md';
touch 'Section 4- IAM & AWS CLI/30. IAM Summary.md';
touch 'Section 4- IAM & AWS CLI/Quiz 1- IAM & AWS CLI Quiz.md';
mkdir -p 'Section 5- EC2 Fundamentals';
touch 'Section 5- EC2 Fundamentals/31. AWS Budget Setup.md';
touch 'Section 5- EC2 Fundamentals/32. EC2 Basics.md';
touch 'Section 5- EC2 Fundamentals/33. Create an EC2 Instance with EC2 User Data to have a Website Hands On.md';
touch 'Section 5- EC2 Fundamentals/34. EC2 Instance Types Basics.md';
touch 'Section 5- EC2 Fundamentals/35. Security Groups & Classic Ports Overview.md';
touch 'Section 5- EC2 Fundamentals/36. Security Groups Hands On.md';
touch 'Section 5- EC2 Fundamentals/37. SSH Overview.md';
touch 'Section 5- EC2 Fundamentals/38. How to SSH using Linux or Mac.md';
touch 'Section 5- EC2 Fundamentals/39. How to SSH using Windows.md';
touch 'Section 5- EC2 Fundamentals/40. How to SSH using Windows 10.md';
touch 'Section 5- EC2 Fundamentals/41. SSH Troubleshooting.md';
touch 'Section 5- EC2 Fundamentals/42. EC2 Instance Connect.md';
touch 'Section 5- EC2 Fundamentals/43. EC2 Instance Roles Demo.md';
touch 'Section 5- EC2 Fundamentals/44. EC2 Instance Purchasing Options.md';
touch 'Section 5- EC2 Fundamentals/Quiz 2- EC2 Fundamentals Quiz.md';
mkdir -p 'Section 6- EC2 Instance Storage';
touch 'Section 6- EC2 Instance Storage/45. EBS Overview.md';
touch 'Section 6- EC2 Instance Storage/46. EBS Hands On.md';
touch 'Section 6- EC2 Instance Storage/47. EBS Snapshots.md';
touch 'Section 6- EC2 Instance Storage/48. EBS Snapshots - Hands On.md';
touch 'Section 6- EC2 Instance Storage/49. AMI Overview.md';
touch 'Section 6- EC2 Instance Storage/50. AMI Hands On.md';
touch 'Section 6- EC2 Instance Storage/51. EC2 Instance Store.md';
touch 'Section 6- EC2 Instance Storage/52. EBS Volume Types.md';
touch 'Section 6- EC2 Instance Storage/53. EBS Multi-Attach.md';
touch 'Section 6- EC2 Instance Storage/54. Amazon EFS.md';
touch 'Section 6- EC2 Instance Storage/55. Amazon EFS - Hands On.md';
touch 'Section 6- EC2 Instance Storage/56. EFS vs EBS.md';
touch 'Section 6- EC2 Instance Storage/57. EBS & EFS - Section Cleanup.md';
touch 'Section 6- EC2 Instance Storage/Quiz 3- EC2 Data Management Quiz.md';
mkdir -p 'Section 7- AWS Fundamentals- ELB + ASG';
touch 'Section 7- AWS Fundamentals- ELB + ASG/58. High Availability and Scalability.md';
touch 'Section 7- AWS Fundamentals- ELB + ASG/59. Elastic Load Balancing (ELB) Overview.md';
touch 'Section 7- AWS Fundamentals- ELB + ASG/60. Note- About the Classic Load Balancer (CLB).md';
touch 'Section 7- AWS Fundamentals- ELB + ASG/61. Application Load Balancer (ALB).md';
touch 'Section 7- AWS Fundamentals- ELB + ASG/62. Application Load Balancer (ALB) - Hands On - Part 1.md';
touch 'Section 7- AWS Fundamentals- ELB + ASG/63. Application Load Balancer (ALB) - Hands On - Part 2.md';
touch 'Section 7- AWS Fundamentals- ELB + ASG/64. Network Load Balancer (NLB).md';
touch 'Section 7- AWS Fundamentals- ELB + ASG/65. Network Load Balancer (NLB) - Hands On.md';
touch 'Section 7- AWS Fundamentals- ELB + ASG/66. Gateway Load Balancer (GWLB).md';
touch 'Section 7- AWS Fundamentals- ELB + ASG/67. Elastic Load Balancer - Sticky Sessions.md';
touch 'Section 7- AWS Fundamentals- ELB + ASG/68. Elastic Load Balancer - Cross Zone Load Balancing.md';
touch 'Section 7- AWS Fundamentals- ELB + ASG/69. Elastic Load Balancer - SSL Certificates.md';
touch 'Section 7- AWS Fundamentals- ELB + ASG/70. Elastic Load Balancer - SSL Certificates - Hands On.md';
touch 'Section 7- AWS Fundamentals- ELB + ASG/71. Elastic Load Balancer - Connection Draining.md';
touch 'Section 7- AWS Fundamentals- ELB + ASG/72. Auto Scaling Groups (ASG) Overview.md';
touch 'Section 7- AWS Fundamentals- ELB + ASG/73. Auto Scaling Groups Hands On.md';
touch 'Section 7- AWS Fundamentals- ELB + ASG/74. Auto Scaling Groups - Scaling Policies.md';
touch 'Section 7- AWS Fundamentals- ELB + ASG/75. Auto Scaling Groups - Scaling Policies Hands On.md';
touch 'Section 7- AWS Fundamentals- ELB + ASG/76. Auto Scaling Groups - Instance Refresh.md';
touch 'Section 7- AWS Fundamentals- ELB + ASG/Quiz 4- High Availability & Scalability Quiz.md';
mkdir -p 'Section 8- AWS Fundamentals- RDS + Aurora + ElastiCache';
touch 'Section 8- AWS Fundamentals- RDS + Aurora + ElastiCache/77. Amazon RDS Overview.md';
touch 'Section 8- AWS Fundamentals- RDS + Aurora + ElastiCache/78. RDS Read Replicas vs Multi AZ.md';
touch 'Section 8- AWS Fundamentals- RDS + Aurora + ElastiCache/79. Amazon RDS Hands On.md';
touch 'Section 8- AWS Fundamentals- RDS + Aurora + ElastiCache/80. Amazon Aurora.md';
touch 'Section 8- AWS Fundamentals- RDS + Aurora + ElastiCache/81. Amazon Aurora - Hands On.md';
touch 'Section 8- AWS Fundamentals- RDS + Aurora + ElastiCache/82. RDS & Aurora Security.md';
touch 'Section 8- AWS Fundamentals- RDS + Aurora + ElastiCache/83. RDS Proxy.md';
touch 'Section 8- AWS Fundamentals- RDS + Aurora + ElastiCache/84. ElastiCache Overview.md';
touch 'Section 8- AWS Fundamentals- RDS + Aurora + ElastiCache/85. ElastiCache Hands On.md';
touch 'Section 8- AWS Fundamentals- RDS + Aurora + ElastiCache/86. ElastiCache Strategies.md';
touch 'Section 8- AWS Fundamentals- RDS + Aurora + ElastiCache/87. Amazon MemoryDB for Redis - Overview.md';
touch 'Section 8- AWS Fundamentals- RDS + Aurora + ElastiCache/Quiz 5- RDS, Aurora, & ElastiCache Quiz.md';
mkdir -p 'Section 9- Route 53';
touch 'Section 9- Route 53/88. What is a DNS-.md';
touch 'Section 9- Route 53/89. Route 53 Overview.md';
touch 'Section 9- Route 53/90. Route 53 - Registering a domain.md';
touch 'Section 9- Route 53/91. Route 53 - Creating our first records.md';
touch 'Section 9- Route 53/92. Route 53 - EC2 Setup.md';
touch 'Section 9- Route 53/93. Route 53 - TTL.md';
touch 'Section 9- Route 53/94. Route 53 CNAME vs Alias.md';
touch 'Section 9- Route 53/95. Routing Policy - Simple.md';
touch 'Section 9- Route 53/96. Routing Policy - Weighted.md';
touch 'Section 9- Route 53/97. Routing Policy - Latency.md';
touch 'Section 9- Route 53/98. Route 53 Health Checks.md';
touch 'Section 9- Route 53/99. Route 53 - Health Checks Hands On.md';
touch 'Section 9- Route 53/100. Routing Policy - Failover.md';
touch 'Section 9- Route 53/101. Routing Policy - Geolocation.md';
touch 'Section 9- Route 53/102. Routing Policy - Geoproximity.md';
touch 'Section 9- Route 53/103. Routing Policy - IP-based.md';
touch 'Section 9- Route 53/104. Routing Policy - Multi Value.md';
touch 'Section 9- Route 53/105. 3rd Party Domains & Route 53.md';
touch 'Section 9- Route 53/106. Route 53 - Section Cleanup.md';
touch 'Section 9- Route 53/Quiz 6- Route 53 Quiz.md';
mkdir -p 'Section 10- VPC Fundamentals';
touch 'Section 10- VPC Fundamentals/107. VPC Fundamentals - Section Introduction.md';
touch 'Section 10- VPC Fundamentals/108. VPC, Subnets, IGW and NAT.md';
touch 'Section 10- VPC Fundamentals/109. NACL, SG, VPC Flow Logs.md';
touch 'Section 10- VPC Fundamentals/110. VPC Peering, Endpoints, VPN, DX.md';
touch 'Section 10- VPC Fundamentals/111. VPC Cheat Sheet & Closing Comments.md';
touch 'Section 10- VPC Fundamentals/112. Three Tier Architecture.md';
touch 'Section 10- VPC Fundamentals/Quiz 7- VPC Quiz.md';
mkdir -p 'Section 11- Amazon S3 Introduction';
touch 'Section 11- Amazon S3 Introduction/113. S3 Overview.md';
touch 'Section 11- Amazon S3 Introduction/114. S3 Hands On.md';
touch 'Section 11- Amazon S3 Introduction/115. S3 Security- Bucket Policy.md';
touch 'Section 11- Amazon S3 Introduction/116. S3 Security- Bucket Policy Hands On.md';
touch 'Section 11- Amazon S3 Introduction/117. S3 Website Overview.md';
touch 'Section 11- Amazon S3 Introduction/118. S3 Website Hands On.md';
touch 'Section 11- Amazon S3 Introduction/119. S3 Versioning.md';
touch 'Section 11- Amazon S3 Introduction/120. S3 Versioning - Hands On.md';
touch 'Section 11- Amazon S3 Introduction/121. S3 Replication.md';
touch 'Section 11- Amazon S3 Introduction/122. S3 Replication Notes.md';
touch 'Section 11- Amazon S3 Introduction/123. S3 Replication - Hands On.md';
touch 'Section 11- Amazon S3 Introduction/124. S3 Storage Classes Overview.md';
touch 'Section 11- Amazon S3 Introduction/125. S3 Storage Classes Hands On.md';
touch 'Section 11- Amazon S3 Introduction/Quiz 8- Amazon S3 Quiz.md';
mkdir -p 'Section 12- AWS CLI, SDK, IAM Roles & Policies';
touch 'Section 12- AWS CLI, SDK, IAM Roles & Policies/126. AWS EC2 Instance Metadata.md';
touch 'Section 12- AWS CLI, SDK, IAM Roles & Policies/127. AWS EC2 Instance Metadata - Hands On.md';
touch 'Section 12- AWS CLI, SDK, IAM Roles & Policies/128. AWS CLI Profiles.md';
touch 'Section 12- AWS CLI, SDK, IAM Roles & Policies/129. AWS CLI with MFA.md';
touch 'Section 12- AWS CLI, SDK, IAM Roles & Policies/130. AWS SDK Overview.md';
touch 'Section 12- AWS CLI, SDK, IAM Roles & Policies/131. Exponential Backoff & Service Limit Increase.md';
touch 'Section 12- AWS CLI, SDK, IAM Roles & Policies/132. AWS Signature v4 Signing (Sigv4).md';
touch 'Section 12- AWS CLI, SDK, IAM Roles & Policies/Quiz 9- AWS IAM, CLI, & SDK Quiz.md';
mkdir -p 'Section 13- Advanced Amazon S3';
touch 'Section 13- Advanced Amazon S3/133. S3 Lifecycle Rules (with S3 Analytics).md';
touch 'Section 13- Advanced Amazon S3/134. S3 Lifecycle Rules - Hands On.md';
touch 'Section 13- Advanced Amazon S3/135. S3 Event Notifications.md';
touch 'Section 13- Advanced Amazon S3/136. S3 Event Notifications - Hands On.md';
touch 'Section 13- Advanced Amazon S3/137. S3 Performance.md';
touch 'Section 13- Advanced Amazon S3/138. S3 Object Tags & Metadata.md';
touch 'Section 13- Advanced Amazon S3/Quiz 10- Amazon S3 Advanced Quiz.md';
mkdir -p 'Section 14- Amazon S3 Security';
touch 'Section 14- Amazon S3 Security/139. S3 Encryption.md';
touch 'Section 14- Amazon S3 Security/140. About DSSE-KMS.md';
touch 'Section 14- Amazon S3 Security/141. S3 Encryption - Hands On.md';
touch 'Section 14- Amazon S3 Security/142. S3 Default Encryption.md';
touch 'Section 14- Amazon S3 Security/143. S3 CORS.md';
touch 'Section 14- Amazon S3 Security/144. S3 CORS Hands On.md';
touch 'Section 14- Amazon S3 Security/145. S3 MFA Delete.md';
touch 'Section 14- Amazon S3 Security/146. S3 MFA Delete Hands On.md';
touch 'Section 14- Amazon S3 Security/147. S3 Access Logs.md';
touch 'Section 14- Amazon S3 Security/148. S3 Access Logs - Hands On.md';
touch 'Section 14- Amazon S3 Security/149. S3 Pre-signed URLs.md';
touch 'Section 14- Amazon S3 Security/150. S3 Pre-signed URLs - Hands On.md';
touch 'Section 14- Amazon S3 Security/151. S3 Access Points.md';
touch 'Section 14- Amazon S3 Security/152. S3 Object Lambda.md';
touch 'Section 14- Amazon S3 Security/Quiz 11- Amazon S3 Security Quiz.md';
mkdir -p 'Section 15- CloudFront';
touch 'Section 15- CloudFront/153. CloudFront - Overview.md';
touch 'Section 15- CloudFront/154. CloudFront Hands On.md';
touch 'Section 15- CloudFront/155. CloudFront - Caching & Caching Policies.md';
touch 'Section 15- CloudFront/156. CloudFront - Cache Invalidations.md';
touch 'Section 15- CloudFront/157. CloudFront - Cache Behaviors.md';
touch 'Section 15- CloudFront/158. CloudFront - Caching & Caching Invalidations - Hands On.md';
touch 'Section 15- CloudFront/159. CloudFront - ALB-EC2 as an Origin.md';
touch 'Section 15- CloudFront/160. CloudFront - Geo Restriction.md';
touch 'Section 15- CloudFront/161. CloudFront Signed URL - Cookies.md';
touch 'Section 15- CloudFront/162. CloudFront Signed URL - Key Groups + Hands On.md';
touch 'Section 15- CloudFront/163. CloudFront Advanced Concepts.md';
touch 'Section 15- CloudFront/164. CloudFront - Real Time Logs.md';
touch 'Section 15- CloudFront/Quiz 12- CloudFront Quiz.md';
mkdir -p 'Section 16- ECS, ECR & Fargate - Docker in AWS';
touch 'Section 16- ECS, ECR & Fargate - Docker in AWS/165. Docker Introduction.md';
touch 'Section 16- ECS, ECR & Fargate - Docker in AWS/166. Amazon ECS.md';
touch 'Section 16- ECS, ECR & Fargate - Docker in AWS/167. Creating ECS Cluster - Hands On.md';
touch 'Section 16- ECS, ECR & Fargate - Docker in AWS/168. Creating ECS Service - Hands On.md';
touch 'Section 16- ECS, ECR & Fargate - Docker in AWS/169. Amazon ECS - Auto Scaling.md';
touch 'Section 16- ECS, ECR & Fargate - Docker in AWS/170. Amazon ECS - Rolling Updates.md';
touch 'Section 16- ECS, ECR & Fargate - Docker in AWS/171. Amazon ECS - Solutions Architectures.md';
touch 'Section 16- ECS, ECR & Fargate - Docker in AWS/172. Amazon ECS Task Definitions - Deep Dive.md';
touch 'Section 16- ECS, ECR & Fargate - Docker in AWS/173. Amazon ECS Task Definitions - Hands On.md';
touch 'Section 16- ECS, ECR & Fargate - Docker in AWS/174. Amazon ECS - Task Placements.md';
touch 'Section 16- ECS, ECR & Fargate - Docker in AWS/175. Amazon ECS - Clean Up - Hands On.md';
touch 'Section 16- ECS, ECR & Fargate - Docker in AWS/176. Amazon ECR.md';
touch 'Section 16- ECS, ECR & Fargate - Docker in AWS/177. Amazon ECR - Hands On.md';
touch 'Section 16- ECS, ECR & Fargate - Docker in AWS/178. AWS CoPilot - Overview.md';
touch 'Section 16- ECS, ECR & Fargate - Docker in AWS/179. AWS CoPilot - Hands On.md';
touch 'Section 16- ECS, ECR & Fargate - Docker in AWS/180. Amazon EKS.md';
touch 'Section 16- ECS, ECR & Fargate - Docker in AWS/Quiz 13- Containers on AWS Quiz.md';
mkdir -p 'Section 17- AWS Elastic Beanstalk';
touch 'Section 17- AWS Elastic Beanstalk/181. AWS Elastic Beanstalk - Section Introduction.md';
touch 'Section 17- AWS Elastic Beanstalk/182. Elastic Beanstalk Overview (High level).md';
touch 'Section 17- AWS Elastic Beanstalk/183. Beanstalk First Environment.md';
touch 'Section 17- AWS Elastic Beanstalk/184. Beanstalk Second Environment.md';
touch 'Section 17- AWS Elastic Beanstalk/185. Beanstalk Deployment Modes.md';
touch 'Section 17- AWS Elastic Beanstalk/186. Beanstalk Deployment Modes Hands On.md';
touch 'Section 17- AWS Elastic Beanstalk/187. Beanstalk CLI and Deployment Process.md';
touch 'Section 17- AWS Elastic Beanstalk/188. Beanstalk Lifecycle Policy Overview + Hands On.md';
touch 'Section 17- AWS Elastic Beanstalk/189. Beanstalk Extensions.md';
touch 'Section 17- AWS Elastic Beanstalk/190. Beanstalk & CloudFormation.md';
touch 'Section 17- AWS Elastic Beanstalk/191. Beanstalk Cloning.md';
touch 'Section 17- AWS Elastic Beanstalk/192. Beanstalk Migrations.md';
touch 'Section 17- AWS Elastic Beanstalk/193. Beanstalk Cleanup.md';
touch 'Section 17- AWS Elastic Beanstalk/Quiz 14- Elastic Beanstalk Quiz.md';
mkdir -p 'Section 18- AWS CloudFormation';
touch 'Section 18- AWS CloudFormation/194. CloudFormation - Overview.md';
touch 'Section 18- AWS CloudFormation/195. CloudFormation - Create Stack - Hands On.md';
touch 'Section 18- AWS CloudFormation/196. CloudFormation - Update & Delete Stack - Hands On.md';
touch 'Section 18- AWS CloudFormation/197. YAML Crash Course.md';
touch 'Section 18- AWS CloudFormation/198. CloudFormation - Resources.md';
touch 'Section 18- AWS CloudFormation/199. CloudFormation - Parameters.md';
touch 'Section 18- AWS CloudFormation/200. CloudFormation - Mappings.md';
touch 'Section 18- AWS CloudFormation/201. CloudFormation - Outputs & Exports.md';
touch 'Section 18- AWS CloudFormation/202. CloudFormation - Conditions.md';
touch 'Section 18- AWS CloudFormation/203. CloudFormation - Intrinsic Functions.md';
touch 'Section 18- AWS CloudFormation/204. CloudFormation - Rollbacks.md';
touch 'Section 18- AWS CloudFormation/205. CloudFormation - Service Role.md';
touch 'Section 18- AWS CloudFormation/206. CloudFormation - Capabilities.md';
touch 'Section 18- AWS CloudFormation/207. CloudFormation - Deletion Policy.md';
touch 'Section 18- AWS CloudFormation/208. CloudFormation - Stack Policy.md';
touch 'Section 18- AWS CloudFormation/209. CloudFormation - Termination Protection.md';
touch 'Section 18- AWS CloudFormation/210. CloudFormation - Custom Resources.md';
touch 'Section 18- AWS CloudFormation/211. CloudFormation - StackSets.md';
touch 'Section 18- AWS CloudFormation/Quiz 15- CloudFormation Quiz.md';
mkdir -p 'Section 19- AWS Integration & Messaging- SQS, SNS & Kinesis';
touch 'Section 19- AWS Integration & Messaging- SQS, SNS & Kinesis/212. AWS Integration & Messaging - Section Introduction.md';
touch 'Section 19- AWS Integration & Messaging- SQS, SNS & Kinesis/213. Introduction to Messaging.md';
touch 'Section 19- AWS Integration & Messaging- SQS, SNS & Kinesis/214. Amazon SQS - Standard Queues Overview.md';
touch 'Section 19- AWS Integration & Messaging- SQS, SNS & Kinesis/215. SQS - Standard Queue Hands On.md';
touch 'Section 19- AWS Integration & Messaging- SQS, SNS & Kinesis/216. SQS Queue Access Policy.md';
touch 'Section 19- AWS Integration & Messaging- SQS, SNS & Kinesis/217. SQS - Message Visibility Timeout.md';
touch 'Section 19- AWS Integration & Messaging- SQS, SNS & Kinesis/218. SQS - Dead Letter Queues.md';
touch 'Section 19- AWS Integration & Messaging- SQS, SNS & Kinesis/219. SQS - Dead Letter Queues - Hands On.md';
touch 'Section 19- AWS Integration & Messaging- SQS, SNS & Kinesis/220. SQS - Delay Queues.md';
touch 'Section 19- AWS Integration & Messaging- SQS, SNS & Kinesis/221. SQS - Certified Developer concepts.md';
touch 'Section 19- AWS Integration & Messaging- SQS, SNS & Kinesis/222. SQS - FIFO Queues.md';
touch 'Section 19- AWS Integration & Messaging- SQS, SNS & Kinesis/223. SQS - FIFO Queues Advanced.md';
touch 'Section 19- AWS Integration & Messaging- SQS, SNS & Kinesis/224. Amazon SNS.md';
touch 'Section 19- AWS Integration & Messaging- SQS, SNS & Kinesis/225. Amazon SNS and SQS - Fan Out Pattern.md';
touch 'Section 19- AWS Integration & Messaging- SQS, SNS & Kinesis/226. SNS Hands On.md';
touch 'Section 19- AWS Integration & Messaging- SQS, SNS & Kinesis/227. Amazon Kinesis Data Streams.md';
touch 'Section 19- AWS Integration & Messaging- SQS, SNS & Kinesis/228. Amazon Kinesis Data Streams - Hands On.md';
touch 'Section 19- AWS Integration & Messaging- SQS, SNS & Kinesis/229. Amazon Data Firehose.md';
touch 'Section 19- AWS Integration & Messaging- SQS, SNS & Kinesis/230. Amazon Data Firehose - Hands On.md';
touch 'Section 19- AWS Integration & Messaging- SQS, SNS & Kinesis/231. Amazon Managed Service for Apache Flink.md';
touch 'Section 19- AWS Integration & Messaging- SQS, SNS & Kinesis/232. SQS vs SNS vs Kinesis.md';
touch 'Section 19- AWS Integration & Messaging- SQS, SNS & Kinesis/Quiz 16- Messaging & Integration Quiz.md';
mkdir -p 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/233. AWS Monitoring - Section Introduction.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/234. Monitoring Overview in AWS.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/235. CloudWatch Metrics.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/236. CloudWatch Custom Metrics.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/237. CloudWatch Logs.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/238. CloudWatch Logs - Hands On.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/239. CloudWatch Logs - Live Tail - Hands On.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/240. CloudWatch Agent & CloudWatch Logs Agent.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/241. CloudWatch Logs - Metric Filters.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/242. CloudWatch Logs - Metric Filters Hands On.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/243. CloudWatch Alarms.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/244. CloudWatch Alarms Hands On.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/245. CloudWatch Synthetics.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/246. Amazon EventBridge.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/247. Amazon EventBridge - Hands On.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/248. Amazon EventBridge - Multi-Account Aggregation.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/249. X-Ray Overview.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/250. X-Ray Hands On.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/251. X-Ray- Instrumentation and Concepts.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/252. X-Ray- Sampling Rules.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/253. X-Ray APIs.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/254. X-Ray with Beanstalk.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/255. X-Ray & ECS.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/256. AWS Distro for OpenTelemetry.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/257. CloudTrail.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/258. CloudTrail Hands On.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/259. CloudTrail - EventBridge Integration.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/260. CloudTrail vs CloudWatch vs X-Ray.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/261. AWS Quick Clean-Up.md';
touch 'Section 20- AWS Monitoring & Audit- CloudWatch, X-Ray and CloudTrail/Quiz 17- Monitoring & Audit Quiz.md';
mkdir -p 'Section 21- AWS Serverless- Lambda';
touch 'Section 21- AWS Serverless- Lambda/262. AWS Lambda - Section Introduction.md';
touch 'Section 21- AWS Serverless- Lambda/263. Serverless Introduction.md';
touch 'Section 21- AWS Serverless- Lambda/264. AWS Lambda Overview.md';
touch 'Section 21- AWS Serverless- Lambda/265. AWS Lambda - First Hands On.md';
touch 'Section 21- AWS Serverless- Lambda/266. Lambda Synchronous Invocations.md';
touch 'Section 21- AWS Serverless- Lambda/267. Lambda Synchronous Invocations Hands On.md';
touch 'Section 21- AWS Serverless- Lambda/268. Lambda & Application Load Balancer.md';
touch 'Section 21- AWS Serverless- Lambda/269. Lambda & Application Load Balancer Hands On.md';
touch 'Section 21- AWS Serverless- Lambda/270. Lambda Asynchronous Invocations & DLQ.md';
touch 'Section 21- AWS Serverless- Lambda/271. Lambda Asynchronous Invocations Hands On.md';
touch 'Section 21- AWS Serverless- Lambda/272. Lambda & CloudWatch Events - EventBridge.md';
touch 'Section 21- AWS Serverless- Lambda/273. Lambda & CloudWatch Events - EventBridge Hands On.md';
touch 'Section 21- AWS Serverless- Lambda/274. Lambda & S3 Event Notifications.md';
touch 'Section 21- AWS Serverless- Lambda/275. Lambda & S3 Event Notifications - Hands On.md';
touch 'Section 21- AWS Serverless- Lambda/276. Lambda Event Source Mapping.md';
touch 'Section 21- AWS Serverless- Lambda/277. Lambda Event Source Mapping Hands On (SQS).md';
touch 'Section 21- AWS Serverless- Lambda/278. Lambda Event & Context Objects.md';
touch 'Section 21- AWS Serverless- Lambda/279. Lambda Destinations.md';
touch 'Section 21- AWS Serverless- Lambda/280. Lambda Destinations Hands On.md';
touch 'Section 21- AWS Serverless- Lambda/281. Lambda Permissions - IAM Roles & Resource Policies.md';
touch 'Section 21- AWS Serverless- Lambda/282. Lambda Permissions - IAM Roles & Resource Policies - Hands On.md';
touch 'Section 21- AWS Serverless- Lambda/283. Lambda Environment Variables.md';
touch 'Section 21- AWS Serverless- Lambda/284. Lambda Environment Variables - Hands On.md';
touch 'Section 21- AWS Serverless- Lambda/285. Lambda Monitoring & X-Ray Tracing.md';
touch 'Section 21- AWS Serverless- Lambda/286. Lambda Monitoring & X-Ray Tracing - Hands On.md';
touch 'Section 21- AWS Serverless- Lambda/287. Lambda@Edge & CloudFront Functions.md';
touch 'Section 21- AWS Serverless- Lambda/288. Lambda in VPC.md';
touch 'Section 21- AWS Serverless- Lambda/289. Lambda in VPC - Hands On.md';
touch 'Section 21- AWS Serverless- Lambda/290. Lambda Function Performance.md';
touch 'Section 21- AWS Serverless- Lambda/291. Lambda Function Performance - Hands On.md';
touch 'Section 21- AWS Serverless- Lambda/292. Lambda Layers.md';
touch 'Section 21- AWS Serverless- Lambda/293. Lambda Layers - Hands On.md';
touch 'Section 21- AWS Serverless- Lambda/294. Lambda File Systems Mounting.md';
touch 'Section 21- AWS Serverless- Lambda/295. Lambda Concurrency.md';
touch 'Section 21- AWS Serverless- Lambda/296. Lambda Concurrency Hands On.md';
touch 'Section 21- AWS Serverless- Lambda/297. Lambda External Dependencies.md';
touch 'Section 21- AWS Serverless- Lambda/298. Lambda External Dependencies - Hands On.md';
touch 'Section 21- AWS Serverless- Lambda/299. Lambda and CloudFormation.md';
touch 'Section 21- AWS Serverless- Lambda/300. Lambda and CloudFormation - Hands On.md';
touch 'Section 21- AWS Serverless- Lambda/301. Lambda Container Images.md';
touch 'Section 21- AWS Serverless- Lambda/302. Lambda Versions and Aliases.md';
touch 'Section 21- AWS Serverless- Lambda/303. Lambda Versions and Aliases - Hands On.md';
touch 'Section 21- AWS Serverless- Lambda/304. Lambda and CodeDeploy.md';
touch 'Section 21- AWS Serverless- Lambda/305. Lambda Function URL.md';
touch 'Section 21- AWS Serverless- Lambda/306. Lambda Function URL - Hands On.md';
touch 'Section 21- AWS Serverless- Lambda/307. Lambda Limits.md';
touch 'Section 21- AWS Serverless- Lambda/308. Lambda Best Practices.md';
touch 'Section 21- AWS Serverless- Lambda/Quiz 18- Lambda Quiz.md';
mkdir -p 'Section 22- AWS Serverless- DynamoDB';
touch 'Section 22- AWS Serverless- DynamoDB/309. DynamoDB - Section Introduction.md';
touch 'Section 22- AWS Serverless- DynamoDB/310. DynamoDB Overview.md';
touch 'Section 22- AWS Serverless- DynamoDB/311. DynamoDB Basics - Hands On.md';
touch 'Section 22- AWS Serverless- DynamoDB/312. DynamoDB WCU & RCU - Throughput.md';
touch 'Section 22- AWS Serverless- DynamoDB/313. DynamoDB WCU & RCU - Hands On.md';
touch 'Section 22- AWS Serverless- DynamoDB/314. DynamoDB - Basic Operations.md';
touch 'Section 22- AWS Serverless- DynamoDB/315. DynamoDB Basic APIs - Hands On.md';
touch 'Section 22- AWS Serverless- DynamoDB/316. DynamoDB - Conditional Writes.md';
touch 'Section 22- AWS Serverless- DynamoDB/317. DynamoDB Indexes (GSI + LSI).md';
touch 'Section 22- AWS Serverless- DynamoDB/318. DynamoDB Indexes (GSI + LSI) - Hands On.md';
touch 'Section 22- AWS Serverless- DynamoDB/319. DynamoDB PartiQL.md';
touch 'Section 22- AWS Serverless- DynamoDB/320. DynamoDB Optimistic Locking.md';
touch 'Section 22- AWS Serverless- DynamoDB/321. DynamoDB DAX.md';
touch 'Section 22- AWS Serverless- DynamoDB/322. DynamoDB DAX - Hands On.md';
touch 'Section 22- AWS Serverless- DynamoDB/323. DynamoDB Streams.md';
touch 'Section 22- AWS Serverless- DynamoDB/324. DynamoDB Streams - Hands On.md';
touch 'Section 22- AWS Serverless- DynamoDB/325. DynamoDB TTL.md';
touch 'Section 22- AWS Serverless- DynamoDB/326. DynamoDB CLI.md';
touch 'Section 22- AWS Serverless- DynamoDB/327. DynamoDB Transactions.md';
touch 'Section 22- AWS Serverless- DynamoDB/328. DynamoDB Session State.md';
touch 'Section 22- AWS Serverless- DynamoDB/329. DynamoDB Partitioning Strategies.md';
touch 'Section 22- AWS Serverless- DynamoDB/330. DynamoDB Conditional Writes, Concurrent Writes & Atomic Writes.md';
touch 'Section 22- AWS Serverless- DynamoDB/331. DynamoDB Patterns with S3.md';
touch 'Section 22- AWS Serverless- DynamoDB/332. DynamoDB Operations.md';
touch 'Section 22- AWS Serverless- DynamoDB/333. DynamoDB Security & Other.md';
touch 'Section 22- AWS Serverless- DynamoDB/Quiz 19- DynamoDB Quiz.md';
mkdir -p 'Section 23- AWS Serverless- API Gateway';
touch 'Section 23- AWS Serverless- API Gateway/334. API Gateway - Section Introduction.md';
touch 'Section 23- AWS Serverless- API Gateway/335. API Gateway Overview.md';
touch 'Section 23- AWS Serverless- API Gateway/336. API Gateway Basics Hands On.md';
touch 'Section 23- AWS Serverless- API Gateway/337. API Gateway Stages and Deployment.md';
touch 'Section 23- AWS Serverless- API Gateway/338. API Gateway Stages and Deployment Hands On.md';
touch 'Section 23- AWS Serverless- API Gateway/339. API Gateway Stages Configurations Hands On.md';
touch 'Section 23- AWS Serverless- API Gateway/340. API Gateway Canary Deployments.md';
touch 'Section 23- AWS Serverless- API Gateway/341. API Gateway Canary Deployments Hands On.md';
touch 'Section 23- AWS Serverless- API Gateway/342. API Gateway Integration Types & Mappings.md';
touch 'Section 23- AWS Serverless- API Gateway/343. API Gateway Mapping Templates Hands On.md';
touch 'Section 23- AWS Serverless- API Gateway/344. API Gateway Open API.md';
touch 'Section 23- AWS Serverless- API Gateway/345. API Gateway Open API - Hands On.md';
touch 'Section 23- AWS Serverless- API Gateway/346. API Gateway Caching.md';
touch 'Section 23- AWS Serverless- API Gateway/347. API Gateway Usage Plans & API Keys.md';
touch 'Section 23- AWS Serverless- API Gateway/348. API Gateway Monitoring, Logging and Tracing.md';
touch 'Section 23- AWS Serverless- API Gateway/349. API Gateway CORS.md';
touch 'Section 23- AWS Serverless- API Gateway/350. API Gateway Authentication and Authorization.md';
touch 'Section 23- AWS Serverless- API Gateway/351. API Gateway Authentication and Authorization - Hands On.md';
touch 'Section 23- AWS Serverless- API Gateway/352. API Gateway REST API vs HTTP API.md';
touch 'Section 23- AWS Serverless- API Gateway/353. API Gateway Websocket API.md';
touch 'Section 23- AWS Serverless- API Gateway/354. API Gateway - Architecture.md';
touch 'Section 23- AWS Serverless- API Gateway/Quiz 20- API Gateway Quiz.md';
mkdir -p 'Section 24- AWS CICD- CodeCommit, CodePipeline, CodeBuild, CodeDeploy';
touch 'Section 24- AWS CICD- CodeCommit, CodePipeline, CodeBuild, CodeDeploy/355. AWS CICD - Section Introduction.md';
touch 'Section 24- AWS CICD- CodeCommit, CodePipeline, CodeBuild, CodeDeploy/356. Introduction to CICD in AWS.md';
touch 'Section 24- AWS CICD- CodeCommit, CodePipeline, CodeBuild, CodeDeploy/357. CodeCommit Overview.md';
touch 'Section 24- AWS CICD- CodeCommit, CodePipeline, CodeBuild, CodeDeploy/358. CodeCommit Hands On Part I.md';
touch 'Section 24- AWS CICD- CodeCommit, CodePipeline, CodeBuild, CodeDeploy/359. CodeCommit Hands On Part 2.md';
touch 'Section 24- AWS CICD- CodeCommit, CodePipeline, CodeBuild, CodeDeploy/360. CodePipeline Overview.md';
touch 'Section 24- AWS CICD- CodeCommit, CodePipeline, CodeBuild, CodeDeploy/361. CodePipeline - Hands On - Prerequisite.md';
touch 'Section 24- AWS CICD- CodeCommit, CodePipeline, CodeBuild, CodeDeploy/362. CodePipeline - Hands On.md';
touch 'Section 24- AWS CICD- CodeCommit, CodePipeline, CodeBuild, CodeDeploy/363. CodeBuild Overview.md';
touch 'Section 24- AWS CICD- CodeCommit, CodePipeline, CodeBuild, CodeDeploy/364. CodeBuild Hands On Part I.md';
touch 'Section 24- AWS CICD- CodeCommit, CodePipeline, CodeBuild, CodeDeploy/365. CodeBuild Hands On Part 2.md';
touch 'Section 24- AWS CICD- CodeCommit, CodePipeline, CodeBuild, CodeDeploy/366. CodeDeploy Overview.md';
touch 'Section 24- AWS CICD- CodeCommit, CodePipeline, CodeBuild, CodeDeploy/367. CodeDeploy Hands On.md';
touch 'Section 24- AWS CICD- CodeCommit, CodePipeline, CodeBuild, CodeDeploy/368. CodeDeploy for EC2 and ASG.md';
touch 'Section 24- AWS CICD- CodeCommit, CodePipeline, CodeBuild, CodeDeploy/369. CodeArtifact - Overview.md';
touch 'Section 24- AWS CICD- CodeCommit, CodePipeline, CodeBuild, CodeDeploy/370. CodeArtifact - Hands On.md';
touch 'Section 24- AWS CICD- CodeCommit, CodePipeline, CodeBuild, CodeDeploy/Quiz 21- AWS CICD Quiz.md';
mkdir -p 'Section 25- AWS Serverless- SAM - Serverless Application Model';
touch 'Section 25- AWS Serverless- SAM - Serverless Application Model/371. AWS SAM - Section Introduction.md';
touch 'Section 25- AWS Serverless- SAM - Serverless Application Model/372. SAM Overview.md';
touch 'Section 25- AWS Serverless- SAM - Serverless Application Model/373. SAM - Hands On.md';
touch 'Section 25- AWS Serverless- SAM - Serverless Application Model/374. SAM with DynamoDB - Hands On.md';
touch 'Section 25- AWS Serverless- SAM - Serverless Application Model/375. SAM Policy Templates.md';
touch 'Section 25- AWS Serverless- SAM - Serverless Application Model/376. SAM with CodeDeploy.md';
touch 'Section 25- AWS Serverless- SAM - Serverless Application Model/377. SAM - Local Capabilities.md';
touch 'Section 25- AWS Serverless- SAM - Serverless Application Model/378. SAM - Multiple Environments.md';
touch 'Section 25- AWS Serverless- SAM - Serverless Application Model/Quiz 22- SAM Quiz.md';
mkdir -p 'Section 26- Cloud Development Kit (CDK)';
touch 'Section 26- Cloud Development Kit (CDK)/379. CDK Overview.md';
touch 'Section 26- Cloud Development Kit (CDK)/380. CDK - Hands On.md';
touch 'Section 26- Cloud Development Kit (CDK)/381. CDK - Constructs.md';
touch 'Section 26- Cloud Development Kit (CDK)/382. CDK - Commands & Bootstraping.md';
touch 'Section 26- Cloud Development Kit (CDK)/383. CDK - Unit Testing.md';
touch 'Section 26- Cloud Development Kit (CDK)/Quiz 23- CDK Quiz.md';
mkdir -p 'Section 27- Cognito- Cognito User Pools, Cognito Identity Pools & Cognito Sync';
touch 'Section 27- Cognito- Cognito User Pools, Cognito Identity Pools & Cognito Sync/384. Cognito Overview.md';
touch 'Section 27- Cognito- Cognito User Pools, Cognito Identity Pools & Cognito Sync/385. Cognito User Pools.md';
touch 'Section 27- Cognito- Cognito User Pools, Cognito Identity Pools & Cognito Sync/386. Cognito User Pools Hands On.md';
touch 'Section 27- Cognito- Cognito User Pools, Cognito Identity Pools & Cognito Sync/387. Cognito User Pools - Others.md';
touch 'Section 27- Cognito- Cognito User Pools, Cognito Identity Pools & Cognito Sync/388. Application Load Balancer - User Authentication.md';
touch 'Section 27- Cognito- Cognito User Pools, Cognito Identity Pools & Cognito Sync/389. Cognito Identity Pools.md';
touch 'Section 27- Cognito- Cognito User Pools, Cognito Identity Pools & Cognito Sync/390. Cognito Identity Pools Hands On.md';
touch 'Section 27- Cognito- Cognito User Pools, Cognito Identity Pools & Cognito Sync/391. Cognito User Pools vs Cognito Identity Pools.md';
touch 'Section 27- Cognito- Cognito User Pools, Cognito Identity Pools & Cognito Sync/Quiz 24- Cognito Quiz.md';
mkdir -p 'Section 28- Other Serverless- Step Functions & AppSync';
touch 'Section 28- Other Serverless- Step Functions & AppSync/392. Step Functions Overview.md';
touch 'Section 28- Other Serverless- Step Functions & AppSync/393. Step Functions - Hands On.md';
touch 'Section 28- Other Serverless- Step Functions & AppSync/394. Step Functions - Invoke Lambda - Hands On.md';
touch 'Section 28- Other Serverless- Step Functions & AppSync/395. Step Functions - Error Handling.md';
touch 'Section 28- Other Serverless- Step Functions & AppSync/396. Step Functions - Error Handling Hands On.md';
touch 'Section 28- Other Serverless- Step Functions & AppSync/397. Step Functions - Wait For Task Token.md';
touch 'Section 28- Other Serverless- Step Functions & AppSync/398. Step Functions - Activity Tasks.md';
touch 'Section 28- Other Serverless- Step Functions & AppSync/399. Step Functions - Standard vs Express.md';
touch 'Section 28- Other Serverless- Step Functions & AppSync/400. AppSync Overview.md';
touch 'Section 28- Other Serverless- Step Functions & AppSync/401. AppSync Hands On.md';
touch 'Section 28- Other Serverless- Step Functions & AppSync/402. AWS Amplify.md';
touch 'Section 28- Other Serverless- Step Functions & AppSync/403. AWS Amplify - Hands On.md';
touch 'Section 28- Other Serverless- Step Functions & AppSync/Quiz 25- Other Serverless Quiz.md';
mkdir -p 'Section 29- Advanced Identity';
touch 'Section 29- Advanced Identity/404. STS Overview.md';
touch 'Section 29- Advanced Identity/405. Advanced IAM.md';
touch 'Section 29- Advanced Identity/406. Granting a User Permissions to Pass a Role to an AWS Service.md';
touch 'Section 29- Advanced Identity/407. AWS Directory Services.md';
touch 'Section 29- Advanced Identity/Quiz 26- Advanced IAM Quiz.md';
mkdir -p 'Section 30- AWS Security & Encryption- KMS, Encryption SDK, SSM Parameter Store, IAM & STS';
touch 'Section 30- AWS Security & Encryption- KMS, Encryption SDK, SSM Parameter Store, IAM & STS/408. AWS Security - Section Introduction.md';
touch 'Section 30- AWS Security & Encryption- KMS, Encryption SDK, SSM Parameter Store, IAM & STS/409. Encryption 101.md';
touch 'Section 30- AWS Security & Encryption- KMS, Encryption SDK, SSM Parameter Store, IAM & STS/410. KMS Overview.md';
touch 'Section 30- AWS Security & Encryption- KMS, Encryption SDK, SSM Parameter Store, IAM & STS/411. KMS Hands On w- CLI.md';
touch 'Section 30- AWS Security & Encryption- KMS, Encryption SDK, SSM Parameter Store, IAM & STS/412. KMS Encryption Patterns and Envelope Encryption.md';
touch 'Section 30- AWS Security & Encryption- KMS, Encryption SDK, SSM Parameter Store, IAM & STS/413. Encryption SDK CLI Hands On.md';
touch 'Section 30- AWS Security & Encryption- KMS, Encryption SDK, SSM Parameter Store, IAM & STS/414. KMS Limits.md';
touch 'Section 30- AWS Security & Encryption- KMS, Encryption SDK, SSM Parameter Store, IAM & STS/415. KMS and AWS Lambda Practice.md';
touch 'Section 30- AWS Security & Encryption- KMS, Encryption SDK, SSM Parameter Store, IAM & STS/416. S3 Bucket Key.md';
touch 'Section 30- AWS Security & Encryption- KMS, Encryption SDK, SSM Parameter Store, IAM & STS/417. KMS Key Policies & IAM Principals.md';
touch 'Section 30- AWS Security & Encryption- KMS, Encryption SDK, SSM Parameter Store, IAM & STS/418. CloudHSM Overview.md';
touch 'Section 30- AWS Security & Encryption- KMS, Encryption SDK, SSM Parameter Store, IAM & STS/419. SSM Parameter Store Overview.md';
touch 'Section 30- AWS Security & Encryption- KMS, Encryption SDK, SSM Parameter Store, IAM & STS/420. SSM Parameter Store Hands On (CLI).md';
touch 'Section 30- AWS Security & Encryption- KMS, Encryption SDK, SSM Parameter Store, IAM & STS/421. Secrets Manager - Overview.md';
touch 'Section 30- AWS Security & Encryption- KMS, Encryption SDK, SSM Parameter Store, IAM & STS/422. Secrets Manager - Hands On.md';
touch 'Section 30- AWS Security & Encryption- KMS, Encryption SDK, SSM Parameter Store, IAM & STS/423. SSM Parameter Store vs Secrets Manager.md';
touch 'Section 30- AWS Security & Encryption- KMS, Encryption SDK, SSM Parameter Store, IAM & STS/424. CloudFormation - Secrets Manager & SSM Integration.md';
touch 'Section 30- AWS Security & Encryption- KMS, Encryption SDK, SSM Parameter Store, IAM & STS/425. CloudWatch Logs Encryption.md';
touch 'Section 30- AWS Security & Encryption- KMS, Encryption SDK, SSM Parameter Store, IAM & STS/426. CodeBuild Security.md';
touch 'Section 30- AWS Security & Encryption- KMS, Encryption SDK, SSM Parameter Store, IAM & STS/427. AWS Nitro Enclaves.md';
touch 'Section 30- AWS Security & Encryption- KMS, Encryption SDK, SSM Parameter Store, IAM & STS/Quiz 27- AWS Security & Encryption Quiz.md';
mkdir -p 'Section 31- AWS Other Services';
touch 'Section 31- AWS Other Services/428. AWS Other Services - Section Introduction.md';
touch 'Section 31- AWS Other Services/429. AWS SES.md';
touch 'Section 31- AWS Other Services/430. Amazon OpenSearch Service - Overview.md';
touch 'Section 31- AWS Other Services/431. Amazon Athena - Overview.md';
touch 'Section 31- AWS Other Services/432. Amazon Athena - Hands On.md';
touch 'Section 31- AWS Other Services/433. Amazon MSK - Overview.md';
touch 'Section 31- AWS Other Services/434. Amazon Certificate Manager (ACM).md';
touch 'Section 31- AWS Other Services/435. Amazon Certificate Manager (ACM) Hands On.md';
touch 'Section 31- AWS Other Services/436. ACM Private CA - Overview.md';
touch 'Section 31- AWS Other Services/437. Amazon Macie.md';
touch 'Section 31- AWS Other Services/438. AWS AppConfig - Overview.md';
touch 'Section 31- AWS Other Services/Quiz 28- Other Services Quiz.md';
mkdir -p 'Section 32- AWS Final Cleanup';
touch 'Section 32- AWS Final Cleanup/439. AWS Final Cleanup.md';
touch 'Section 32- AWS Final Cleanup/440. Cleanup Checklist.md';
mkdir -p 'Section 33- Preparing for the Exam - AWS Certified Developer Associate';
touch 'Section 33- Preparing for the Exam - AWS Certified Developer Associate/441. Exam Preparation - Section Introduction.md';
touch 'Section 33- Preparing for the Exam - AWS Certified Developer Associate/442. State of Learning Checkpoint.md';
touch 'Section 33- Preparing for the Exam - AWS Certified Developer Associate/443. Exam Tips - AWS Certified Developer Associate.md';
touch 'Section 33- Preparing for the Exam - AWS Certified Developer Associate/444. Exam Walkthrough and Signup.md';
touch 'Section 33- Preparing for the Exam - AWS Certified Developer Associate/445. Save 50% on your AWS Exam Cost!.md';
touch 'Section 33- Preparing for the Exam - AWS Certified Developer Associate/446. Get an Extra 30 Minutes on your AWS Exam - Non Native English Speakers only.md';
touch 'Section 33- Preparing for the Exam - AWS Certified Developer Associate/Practice Test 1- Practice Test - AWS Certified Developer Associate.md';
mkdir -p 'Section 34- Congratulations - AWS Certified Developer Associate';
touch 'Section 34- Congratulations - AWS Certified Developer Associate/447. AWS Certification Paths.md';
touch 'Section 34- Congratulations - AWS Certified Developer Associate/448. Congratulations.md';
touch 'Section 34- Congratulations - AWS Certified Developer Associate/449. Bonus Lecture.md';
